# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_R=3.3.2
    - CONDA_R=3.4.1
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "D5ri60uGQNOhiGxYOs28I83lFks4aYYuLkfT0judes8b0aL41Gl0rE8Igtt8WxV917wPcxtdIhYGr1mxmsdPRL4RMBfZAhsnsrx4OOv3sMAwQxEWZvCqvJ1wgD/MM3HG50fejKhmWAJIylLFewJIYl/eWRcD7ofyftAhZwGOkLNLn9MX4Yb3pjR8Fn30NuB+oIrED2UmHzuSGYXuQUuucvy5l2G1RXGutM3SQg6iWeoaukwca+9uohPVVmBpfXP6SSF7G3yYqt6moeK3OruNbfXfriJtaGLZZulYrLletuXnm0y6mOZYReWHfK9EwurE27g87miwjpTGr2jYDnVpdFG1gzbLX94/KicE9w77r6pQF7JuIS3rIojRM0KdrWp15ptCzIg7k3KyJhSzPwLky+mB/ATYjOE84h/p/Kt4yE8Lz1kpf3thfHAd+9kxtFUSc72BT3N/su2qYnZ8zpDSuCjToMK7d/s0X03akwQwIqJpC+WeR7nRSvEsfQA3PbWoPllvpAV1LgrwktSlTrJE+NFBMxknwojqZ4NC/REB0v4Zqw4SVuS7XHiUlgqjxErE0UasVROpeTKODmBvXMEv+X03AMO85iwCrDHi49wIj6Gdt4vlScCWHYEw7mZ+V//0OeILKaVw8h6Eto6Bt/u4pEK2XTQXd6ElHSxjvRAJi9Q="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
