travis:
  secure:
    BINSTAR_TOKEN: Ceu32w8p+Yp8GZYSGXGAqnvZs1ore1FzjUEd/0xGJCNoWd+XXNjRXtbg2D9jtKTWXiIKeAfqU41+c7CN38gKWKsHImh8guFDFTsmtbciN7xoDYYFZfC2eAXu5EXxFT5jVkaOMQB0fc/bgkJThcuRmVJAlkT7xU24uopzgIunJooqZfT+3GnOlQk7sKTIPXXv9g+St/pQ5ByPYPj70h7kQhJ9wdKWSDcw0PYLolLWLS++ONBYT9dhcHGatSC4yECS/KkYfdT07LHxteAbKf9KXKgiVgXM6ifPuG+LOyRtQZ55StQ9KOxfddq5bZbfvOlOnxdbIDdsLygT/hr/k38wjtgDsdee9U3ZYDRAqAF6UYkC2s/cB3+1TcbiO/h1OmRDSIAm4g/+YTNyy/X9ofp4eEYRdwafPvhzxW3Ai8F7L8DhZZcSgXpE1vSoEjKiydIwYT0PuDsoS18Vz6FCp5mHsECpvvHtHI5IsfjbgiKCGL82dtEc2OgGHzqermwflQ57KmlAt1DLNfAO+gIWU5DIWFhhnK3Jgecka8regMbEKXk5+v03nI/SUZRMrGro0fbRetYyso2QYDqzfzDw8PJJDOpPl7F5T/pDW83oGpYWEpmaXKEetvIqMOaC+JyYGWO0HFjLwE0J5nUgON2PrZg1MnCC65S/uSItcKA2TPIltsM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
