travis:
  secure:
    BINSTAR_TOKEN: D5ri60uGQNOhiGxYOs28I83lFks4aYYuLkfT0judes8b0aL41Gl0rE8Igtt8WxV917wPcxtdIhYGr1mxmsdPRL4RMBfZAhsnsrx4OOv3sMAwQxEWZvCqvJ1wgD/MM3HG50fejKhmWAJIylLFewJIYl/eWRcD7ofyftAhZwGOkLNLn9MX4Yb3pjR8Fn30NuB+oIrED2UmHzuSGYXuQUuucvy5l2G1RXGutM3SQg6iWeoaukwca+9uohPVVmBpfXP6SSF7G3yYqt6moeK3OruNbfXfriJtaGLZZulYrLletuXnm0y6mOZYReWHfK9EwurE27g87miwjpTGr2jYDnVpdFG1gzbLX94/KicE9w77r6pQF7JuIS3rIojRM0KdrWp15ptCzIg7k3KyJhSzPwLky+mB/ATYjOE84h/p/Kt4yE8Lz1kpf3thfHAd+9kxtFUSc72BT3N/su2qYnZ8zpDSuCjToMK7d/s0X03akwQwIqJpC+WeR7nRSvEsfQA3PbWoPllvpAV1LgrwktSlTrJE+NFBMxknwojqZ4NC/REB0v4Zqw4SVuS7XHiUlgqjxErE0UasVROpeTKODmBvXMEv+X03AMO85iwCrDHi49wIj6Gdt4vlScCWHYEw7mZ+V//0OeILKaVw8h6Eto6Bt/u4pEK2XTQXd6ElHSxjvRAJi9Q=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
