travis:
  secure:
    BINSTAR_TOKEN: fuIdm6UkxRkDLx399s6X3tdGPg/CthHHaf12WPeYfP4zjtrNrAhJSBpiZJLfdc+7yGm9LLBB6UZg22uOVilHJs0B7ABa4+BSP5wK+argr/y5/zf0MO1lI/oh2vrNIYfV4JV+oqUNk6lOcoCKPJ60//umeRYR+IsL9/zWl9Ive4TP9L895LjIEh2DaZ25qRIOet6uNv1KiClovSgs0KhNgN1pekvSZwrz6tP8n9iTw9HnfH+otZNGhCuXxkNsvQo9nnLVHM6adph2D4OARQ47Zqu3yeBu6BFFhxl1f4R7nTrlXmLnhDyMMKb1DtORmMlPYWMPwBYWtvoxOGuJVxTOo5Wsp7QQG6Jf1mjCDVA5NhaI1vhwBdUufQNcLYCjk6FuKtiRS90UQUg6rGFMAXe1ALbQn7QGJhGwRTAD8JJam0vZM7OaRRSN4GOJg9uf1ACIGkho2mebW40M/7UiG0hhRaG6aYawbp95bJIFla1WKQJ4rh5QIMPb77Bk1mlCk8gPG6ZEsCgtw4Vn9seD6RpQbIV9njgc3NpRwzqILE/O5Nr/OFN67ayYhVOjZOeovTnmc53zVZGK9hVJW8zb1cZBLmhQAxLi+1mbLlBnHKVmck8sLzN/HogNkvW+oCMun/J2Tg6kehl6t0dFaJajjKivARV5RaKPPGzp9vIpJMxm+C0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
