travis:
  secure:
    BINSTAR_TOKEN: qzNZE5Ozq2v8Ec264iFV0iada0+Q0vLmWEaba9RimGsp6OryeaHjBb2UnEuimZgIVLBxemdxYFh0M2NV7TRyyKFVNXI6dLVLiJiE6fxacOmraAhrycrSPcxXdZ8iv7b4XRLNz25a0VmTOq9ttlm5lsP3O4f//vdSwxoBVPGQoejlLkLQDrur2mcBg2nFkqzcf0LbwagDbvMYxUPzbrLXDFC7Ts+eXQN4oVXAwFioGaCE5nXcep0+wl/RDiU3sd0Saqdsts+8ZZmoidt0QZdFSb+MfHB7MROwQSDEiEjh+ZnCALJK9YD8UxHJq01TOzwkfNpzhLhKMtaOJZUsu+uiUnXAOkbd/rqIiFFhDqf6G4nUcm5AUYr1K5SDZs18OcIDgbaBPVsWCjU7jq68cxPdQt6P5RkIbvyljo5IcYyx/4OyU4tbKY70Z6kFrn0QBGhAxt+hO+zhnyJqiGZIwy2VWN6yRY7cQbQCfHjQRAiHLFd0AvodeGin3BSn4feTuOVEbKKAVGgCk7ikR+DuQaGQEEWhvagjWd2WxMASKq3kLgcQRG9a4LrmTUa+fvAIfzj8fQL90zB9iMngktum0VkbpodPhyH1w1vnqawkXobXO4sNzkxuz+rem63cniVJDfOH/cs2iGXcG5plJ4JP530t7a5JGKu9f2DgyYeKtVqC/rA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
