appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: L7+uzjZjvOUlZv24cy6VnE3x6TLXr1lksW8yZbW5r+JVzqYmSZmckCDm/HOFi2YMLrkVvqnMtm9HHj7fsABvxISxFTurJotPaYMpkul22frV59iaGrqyNnkwxyPWDPUYjoJ1gEEkoYTrHza3Oy13lEmyRBS0mcNsHDQCFzdKEGPCUi82zQl1dwg8tROGlsDO/cebzDs6/c5FpcCDletlbzuuosqlGWrEjWdyKbEmdI91UP8Tgmom4ONc9Z5K8b1ibwbaaMxbi1HlfBKKP+/q5T4n0nJQLG1mKsvw+Yv1wbNph2S3A6wAqcEaZmm4CH+HEgCLjhBgSeNNHQkJ1uRZJS8NlsWwe6HLopZ5KmQ0vm2J4q4m5xH/kHnMRsXlVDXUhTdGnyAXUWcqL0p7KtSXCnPoAUVqU92EB1o89SuHozYyj8eAAls9goL02ucXLtfyk0fWGWwyQv9xoTPudbc9JBflWq50WqTDeyJYrCC7SAeY7tWE3qA29MTxhDX0WYGJYpMyqY10f9KZhC4ntPRtSw3SkVPNwd4Ks7IUxNoH3ibIS65L5YEea+nbCdMfdAHpukHYuk6fabQx4UzMmehxFeQY9APGc5mdQpqUnFsgzvQqw8iaSk9KVI++I6ZDzaKWiMHr1/zH3xhWl33lfJf7epDUp8ww0HvOoXMC2GkDvuw=
